### ISSUE TITLE
Roll out sometimes breaks deployment

### ISSUE THREAD

**Issue by jml** [weaveworks/prism#19]
When we roll out new versions of the ingesters, they sometimes fail to correctly deregister themselves from consul, causing user-visible errors, manifesting as 500s on `/push` requests.

Distributor logs will have messages like:

```
time="2016-09-12T14:12:22Z" level=error msg="error sending request: Post http://10.244.9.10:80/push: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" source="server.go:107" 
```

And the retrieval queues will likely fill up.

You can confirm this is a problem by looking at the distributor logs and observing:

```
time="2016-09-12T15:00:31Z" level=info msg="Got update to ring - 6 ingesters, 512 tokens" source="ring.go:85"
```

Where `6` is higher than the number of actual ingester pods.

The workaround is to restart consul like so:

```
kubectl delete --namespace frankenstein name=consul
```

After a minute or so, the errors in the distributor log should clear.

**Comment by tomwilkie** [comment]
Noticed the newly deployed ingesters have a restart count of 1 - weird.  Got the logs for the previous run, and hey presto:

```
time="2016-09-15T11:06:49Z" level=info msg="Heartbeating to consul..." source="ingester_lifecycle.go:142" 
time="2016-09-15T11:06:49Z" level=info msg="Found empty ring, inserting tokens!" source="ingester_lifecycle.go:128" 
time="2016-09-15T11:06:49Z" level=error msg="Found empty ring when trying to unregister!" source="ingester_lifecycle.go:155" 
panic: assignment to entry in nil map
	panic: Callback must instantiate value!

goroutine 44 [running]:
panic(0xbcbec0, 0xc820650db0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/weaveworks/frankenstein/ring.(*consulClient).CAS(0xc82024cee0, 0xc820baeb50, 0xf, 0x1060ef8, 0xc820ba7650, 0x0, 0x0)
	/go/src/github.com/weaveworks/frankenstein/ring/consul_client.go:132 +0x9ec
github.com/weaveworks/frankenstein/ring.(*prefixedConsulClient).CAS(0xc820259420, 0xeab400, 0x4, 0x1060ef8, 0xc820ba7650, 0x0, 0x0)
	/go/src/github.com/weaveworks/frankenstein/ring/consul_client.go:320 +0xbb
github.com/weaveworks/frankenstein/ring.(*IngesterRegistration).unregister(0xc82023b040, 0xc82030ae00, 0x80, 0x80)
	/go/src/github.com/weaveworks/frankenstein/ring/ingester_lifecycle.go:163 +0xe0
panic(0xbcbec0, 0xc820baeb20)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/weaveworks/frankenstein/ring.(*Desc).addIngester(0xc820b993c0, 0xc820259480, 0x19, 0xc82024cf70, 0xe, 0xc82030ae00, 0x80, 0x80)
	/go/src/github.com/weaveworks/frankenstein/ring/model.go:50 +0xf9
github.com/weaveworks/frankenstein/ring.(*IngesterRegistration).heartbeat.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/frankenstein/ring/ingester_lifecycle.go:129 +0x1c4
github.com/weaveworks/frankenstein/ring.(*consulClient).CAS(0xc82024cee0, 0xc8206500a0, 0xf, 0x1060ef8, 0xc82030c9c0, 0x0, 0x0)
	/go/src/github.com/weaveworks/frankenstein/ring/consul_client.go:122 +0x778
github.com/weaveworks/frankenstein/ring.(*prefixedConsulClient).CAS(0xc820259420, 0xeab400, 0x4, 0x1060ef8, 0xc82030c9c0, 0x0, 0x0)
	/go/src/github.com/weaveworks/frankenstein/ring/consul_client.go:320 +0xbb
github.com/weaveworks/frankenstein/ring.(*IngesterRegistration).heartbeat(0xc82023b040, 0xc82030ae00, 0x80, 0x80)
	/go/src/github.com/weaveworks/frankenstein/ring/ingester_lifecycle.go:143 +0x1eb
github.com/weaveworks/frankenstein/ring.(*IngesterRegistration).loop(0xc82023b040)
	/go/src/github.com/weaveworks/frankenstein/ring/ingester_lifecycle.go:90 +0xe2
created by github.com/weaveworks/frankenstein/ring.RegisterIngester
	/go/src/github.com/weaveworks/frankenstein/ring/ingester_lifecycle.go:71 +0x3a1
```

**Comment by tomwilkie** [comment]
Oh wait, thats because I killed consul to work around this issue.

Still, should fix it.

**Comment by tomwilkie** [comment]
Watching an ingestor shutdown, I note they take ages locally to flush chunks.  So I think this could be improved by flushing more chunks in parallel.

**Comment by juliusv** [comment]
Hm yeah, shutting down an ingester will mean flushing millions of chunks in a production setup. That's why in normal Prometheus shutdown, we only serialize out a single snapshot file, much faster. But that could be problematic if you want to have ingesters and their shard assignments come and go...

**Comment by tomwilkie** [comment]
Its currently very serial, so parallelising is should help.  And I'm hoping we shouldn't have as many chunks to flush as a normal prometheus.

**Comment by juliusv** [comment]
@tomwilkie At least one chunk per series, right? And I'd expect an ingester to have millions of series in the end.

**Comment by tomwilkie** [comment]
Yeah that sounds about right.  I was going to limit parallelism to 1k, and on average its taking 100s of ms to flush, so it will take ~500s to shutdown?

**Comment by juliusv** [comment]
Ugh yeah. Probably nothing we can do though. Even if we wrote out a snapshot somewhere and recovered it later, the data in that snapshot would be unqueriable for many minutes.

**Comment by tomwilkie** [comment]
The ingestor will be query-able whilst they are shutting down / flushing, so its not a big deal.

**Comment by juliusv** [comment]
Yep!

**Comment by tomwilkie** [comment]
Fixes by #23

**Comment by paulbellamy** [comment]
Still happening.
```
panic: assignment to entry in nil map
	panic: Callback must instantiate value!

goroutine 37 [running]:
panic(0xb4e7e0, 0xc820680540)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/tomwilkie/frankenstein/ring.(*consulClient).CAS(0xc8201b2e60, 0xc820ef0770, 0xf, 0xf867f0, 0xc820c91ad0, 0x0, 0x0)
	/go/src/github.com/tomwilkie/frankenstein/ring/consul_client.go:132 +0x9ec
github.com/tomwilkie/frankenstein/ring.(*prefixedConsulClient).CAS(0xc820197a20, 0xdee918, 0x4, 0xf867f0, 0xc820c91ad0, 0x0, 0x0)
	/go/src/github.com/tomwilkie/frankenstein/ring/consul_client.go:320 +0xbb
github.com/tomwilkie/frankenstein/ring.(*IngesterRegistration).unregister(0xc820147ef0, 0xc820295000, 0x80, 0x80)
	/go/src/github.com/tomwilkie/frankenstein/ring/ingester_lifecycle.go:163 +0xe0
panic(0xb4e7e0, 0xc820ef0760)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/tomwilkie/frankenstein/ring.(*Desc).addIngester(0xc8217be780, 0xc820197a80, 0x19, 0xc8201b2ef0, 0xf, 0xc820295000, 0x80, 0x80)
	/go/src/github.com/tomwilkie/frankenstein/ring/model.go:50 +0xf9
github.com/tomwilkie/frankenstein/ring.(*IngesterRegistration).heartbeat.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/tomwilkie/frankenstein/ring/ingester_lifecycle.go:129 +0x1c4
github.com/tomwilkie/frankenstein/ring.(*consulClient).CAS(0xc8201b2e60, 0xc820c883d0, 0xf, 0xf867f0, 0xc8201f3f80, 0x0, 0x0)
	/go/src/github.com/tomwilkie/frankenstein/ring/consul_client.go:122 +0x778
github.com/tomwilkie/frankenstein/ring.(*prefixedConsulClient).CAS(0xc820197a20, 0xdee918, 0x4, 0xf867f0, 0xc8201f3f80, 0x0, 0x0)
	/go/src/github.com/tomwilkie/frankenstein/ring/consul_client.go:320 +0xbb
github.com/tomwilkie/frankenstein/ring.(*IngesterRegistration).heartbeat(0xc820147ef0, 0xc820295000, 0x80, 0x80)
	/go/src/github.com/tomwilkie/frankenstein/ring/ingester_lifecycle.go:143 +0x1eb
github.com/tomwilkie/frankenstein/ring.(*IngesterRegistration).loop(0xc820147ef0)
	/go/src/github.com/tomwilkie/frankenstein/ring/ingester_lifecycle.go:90 +0xe2
created by github.com/tomwilkie/frankenstein/ring.RegisterIngester
	/go/src/github.com/tomwilkie/frankenstein/ring/ingester_lifecycle.go:71 +0x3a1
```

**Comment by jml** [comment]
Since replicating across ingesters, this has ceased to be a practical problem.
